# Generated by Django 6.0.1 on 2026-01-21 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('middlename', models.CharField(blank=True, max_length=100, null=True)),
                ('lastname', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('dateofbirth', models.DateField()),
                ('patientno', models.DecimalField(decimal_places=0, max_digits=10, unique=True)),
                ('registrationdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PatientListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('bmistatus', models.CharField(max_length=50)),
                ('lastassessmentdate', models.DateField()),
                ('patientname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientapp.patientregistration')),
            ],
        ),
        migrations.CreateModel(
            name='OverweightAssment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitdate', models.DateField()),
                ('generalhealth', models.CharField(choices=[('Good', 'Good'), ('Poor', 'Poor')], max_length=5)),
                ('question1', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5)),
                ('comments', models.TextField()),
                ('patientname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientapp.patientregistration')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralAssment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitdate', models.DateField()),
                ('generalhealth', models.CharField(choices=[('Good', 'Good'), ('Poor', 'Poor')], max_length=5)),
                ('question2', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5)),
                ('comments', models.TextField()),
                ('patientname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientapp.patientregistration')),
            ],
        ),
        migrations.CreateModel(
            name='PatientVitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bmistatus', models.CharField(max_length=50)),
                ('visitdate', models.DateField()),
                ('patientname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientapp.patientregistration')),
            ],
        ),
    ]
